/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlosLopezAmaztalli
 */
public class Tabladebasededatos extends javax.swing.JFrame {
    Conexion cc=new Conexion();
    Connection cn=cc.getConnecction();
    private DefaultTableModel model;
    /**
     * Creates new form Tabladebasededatos
     */
    public Tabladebasededatos() {
        initComponents();
        this.setTitle("Envio de producto y administracion de base de datos");
        cargar();
    }
    public void cargar(){
        String[] informacionPedido={"Nombreproducto","Tipoproducto","Cantidadproducto","Nombreproveedor","Sucursal"};
        String[] registros= new String [50];
        
        String sql="SELECT *FROM farmacia";
        
        model = new DefaultTableModel(null,informacionPedido);
        Conexion cc=new Conexion();
        Connection conect =cc.getConnecction();
        try{
            Statement st=(Statement)conect.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                registros[0] =rs.getString("Nombreproducto");
                registros[1] =rs.getString("Tipoproducto");
                registros[2] =rs.getString("Cantidadproducto");
                registros[3] =rs.getString("Nombreproveedor");
                registros[4] =rs.getString("Sucursal");
                
                model.addRow(registros);
                
            }
            TablaBase.setModel(model);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBase = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        botonCerrrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("ENVIANDO PRODUCTO AL LUGAR INDICADO...");
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombreproducto", "Tipoproducto", "Cantidadproducto", "Nombreproveedor", "Sucursal"
            }
        ));
        TablaBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaBaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaBase);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("ENVIANDO PRODUCTO AL LUGAR INDICADO...");
        jScrollPane3.setViewportView(jTextArea2);

        jLabel1.setText("Administracion de la base de datos");

        botonCerrrar.setText("Cerrar ventana");
        botonCerrrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrrarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonEliminar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonCerrrar)
                                        .addGap(27, 27, 27)
                                        .addComponent(botonModificar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrrar)
                    .addComponent(botonModificar))
                .addGap(18, 18, 18)
                .addComponent(botonEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addComponent(jScrollPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaBaseMouseClicked
       
        int fila = TablaBase.getSelectedRow();
        if(fila ==-1){
            JOptionPane.showMessageDialog(null, "no se selecciono fila");
        }else{
            
           String Nombreproducto = (String) TablaBase.getValueAt(fila, 0).toString();
             String Tipoproducto=(String) TablaBase.getValueAt(fila, 1);
             int Cantidadproducto=Integer.parseInt((String)TablaBase.getValueAt(fila, 2).toString());
              String Nombreproveedor=(String) TablaBase.getValueAt(fila, 3);
              String Sucursal=(String) TablaBase.getValueAt(fila, 4);
        }
    }//GEN-LAST:event_TablaBaseMouseClicked

    private void botonCerrrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrrarActionPerformed
         this.dispose();
    }//GEN-LAST:event_botonCerrrarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
          try
        {
            for(int i=0;i<TablaBase.getRowCount();i++)
            {
               
                    PreparedStatement pst=cn.prepareStatement("Update productos set Nombreproducto= '"+"Tipoproducto= '"+"Cantidadproducto= '"+"Nombreproveedor= '"+"Sucursal= '"+"'");
                    pst.setString(1, TablaBase.getValueAt(i, 0).toString());
                    pst.setString(2, TablaBase.getValueAt(i, 1).toString());
                    pst.setString(3, TablaBase.getValueAt(i, 2).toString());
                    pst.setString(4, TablaBase.getValueAt(i, 3).toString());
                    pst.setString(5, TablaBase.getValueAt(i, 4).toString());
                    pst.executeUpdate();  
            }
             }catch(Exception e){
                    System.out.print(e.getMessage());
                    }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int fila =TablaBase.getSelectedRow();
        try{
            if(fila<0){
                JOptionPane.showMessageDialog(null, "producto no seleccionado ");
                
            }else{
               model.removeRow(fila);
                PreparedStatement pst=cn.prepareStatement("delete from farmacia where Nombreproducto="+TablaBase.getValueAt(1, 0));
            
                Conexion cc=new Conexion();
        Connection cn=cc.getConnecction();
       Statement st=cn.createStatement();
       int N= st.executeUpdate(pst.toString());
       if(N>=0){
            JOptionPane.showMessageDialog(null, "producto eliminado ");
       }
        JOptionPane.showMessageDialog(null, "producto eliminado ");
        limpiarTabla();
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_botonEliminarActionPerformed
    void limpiarTabla(){
         int fila2=TablaBase.getSelectedRow();
        if(fila2>=0){
            model.removeRow(fila2);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar fila");
        }
         int elitotal=TablaBase.getRowCount();
        for(int i=elitotal-1;i>=0;i--){
            model.removeRow(i);
        }       
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabladebasededatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabladebasededatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabladebasededatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabladebasededatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabladebasededatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaBase;
    private javax.swing.JButton botonCerrrar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
