/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;
import java.awt.HeadlessException;
import java.util.regex.Pattern;  
import java.util.LinkedList;
import java.lang.Character;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



/**
 *
 * @author CARLOSANTONIOLOPEZAMAZTALLI
 */
public class Ventanaprincipal extends javax.swing.JFrame {
    public static LinkedList contenedor=new LinkedList();
    public int buscar;
   
private Character caracter;


    /**
     * Creates new form Ventanaprincipal
     */
    String textoArchivo;
    int indiceActual;
    int totalPersonas;
    
    public Ventanaprincipal()  {
        initComponents();
        this.setTitle("Farmacia");
     
       // mostrarDatos();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoproveedor = new javax.swing.ButtonGroup();
        grupoSucursal = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        cantidadProductoTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botonBorrar = new javax.swing.JButton();
        GuardarButton = new javax.swing.JButton();
        jtipobox = new javax.swing.JComboBox<>();
        radioBotonTomas = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        checkBotonVilla = new javax.swing.JCheckBox();
        radioBotonRamon = new javax.swing.JRadioButton();
        radioBotonJose = new javax.swing.JRadioButton();
        radioBotonLuis = new javax.swing.JRadioButton();
        RadioBotonHector = new javax.swing.JRadioButton();
        CheckBoxCoatza = new javax.swing.JCheckBox();
        checkBoxSanMartin = new javax.swing.JCheckBox();
        checkBoxSantaIsabel = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nombre del producto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("tipo del producto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Sucursal:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Cantidad del producto:");

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        cantidadProductoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadProductoTextFieldActionPerformed(evt);
            }
        });
        cantidadProductoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadProductoTextFieldKeyTyped(evt);
            }
        });

        botonBorrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        GuardarButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GuardarButton.setText("Guardar");
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(botonBorrar)
                .addGap(121, 121, 121)
                .addComponent(GuardarButton)
                .addContainerGap(986, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(GuardarButton))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jtipobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cubrebocas", "Medicamento", "analgesicos", "pastillas", "Inyecciones", "Cepillo de dientes", "Botiquin" }));
        jtipobox.setSelectedIndex(-1);
        jtipobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtipoboxActionPerformed(evt);
            }
        });

        grupoproveedor.add(radioBotonTomas);
        radioBotonTomas.setText("Tomas Castro\n\n");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Nombre del proveedor:");

        grupoSucursal.add(checkBotonVilla);
        checkBotonVilla.setText("villa laredo");

        grupoproveedor.add(radioBotonRamon);
        radioBotonRamon.setText("ramon hernandez");
        radioBotonRamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonRamonActionPerformed(evt);
            }
        });

        grupoproveedor.add(radioBotonJose);
        radioBotonJose.setText("Jose fernandez");
        radioBotonJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonJoseActionPerformed(evt);
            }
        });

        grupoproveedor.add(radioBotonLuis);
        radioBotonLuis.setText("luis donaldo");

        grupoproveedor.add(RadioBotonHector);
        RadioBotonHector.setText("hector valdilla");

        grupoSucursal.add(CheckBoxCoatza);
        CheckBoxCoatza.setText("coatzacoalcos");
        CheckBoxCoatza.setName(""); // NOI18N

        grupoSucursal.add(checkBoxSanMartin);
        checkBoxSanMartin.setText("san martin");
        checkBoxSanMartin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSanMartinActionPerformed(evt);
            }
        });

        grupoSucursal.add(checkBoxSantaIsabel);
        checkBoxSantaIsabel.setText("Santa Isabel");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Iniciaste Sesion Como:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(checkBotonVilla)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBoxCoatza)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkBoxSanMartin)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkBoxSantaIsabel)
                                        .addGap(93, 93, 93))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(radioBotonTomas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioBotonRamon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioBotonJose)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioBotonLuis)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioBotonHector))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadProductoTextField)
                                    .addComponent(jtipobox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(619, 619, 619)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtipobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(cantidadProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBotonTomas)
                    .addComponent(radioBotonRamon)
                    .addComponent(radioBotonJose)
                    .addComponent(radioBotonLuis)
                    .addComponent(RadioBotonHector)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkBotonVilla)
                    .addComponent(CheckBoxCoatza)
                    .addComponent(checkBoxSanMartin)
                    .addComponent(checkBoxSantaIsabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    @SuppressWarnings("null")
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(this, "¿Esta seguro de borrar los datos introducidos?");
        if(respuesta==JOptionPane.YES_OPTION){
           
        try {
               
            nombreTextField.setText("");
            jtipobox.setSelectedIndex(-1);
            cantidadProductoTextField.setText("");
            radioBotonTomas.setSelected(false);
            radioBotonRamon.setSelected(false);
            radioBotonJose.setSelected(false);
            radioBotonLuis.setSelected(false);
            RadioBotonHector.setSelected(false);
            checkBotonVilla.setSelected(false);
            CheckBoxCoatza.setSelected(false);
            checkBoxSanMartin.setSelected(false);
            checkBoxSantaIsabel.setSelected(false);
            grupoproveedor.clearSelection();
            grupoSucursal.clearSelection();
        } catch (Exception ex) {
            Logger.getLogger(Ventanaprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } 
           JOptionPane.showMessageDialog(this, "Operacion exitosa");
        }        
        
    }//GEN-LAST:event_botonBorrarActionPerformed
   
    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
                Guardar();
    }//GEN-LAST:event_GuardarButtonActionPerformed
    public void Guardar(){
         try{
                  String nombredelproducto= nombreTextField.getText();
                  int Cantidaddelproducto=Integer.parseInt(cantidadProductoTextField.getText());
                  String tipodelproducto= jtipobox.getSelectedItem().toString();
                  String nombredelproveedor=radioBotonTomas.getText();
                  String nombredelproveedor2=radioBotonRamon.getText();
                  String nombredelproveedor3=radioBotonJose.getText();
                  String nombredelproveedor4=radioBotonLuis.getText();
                  String nombredelproveedor5=RadioBotonHector.getText();
                  String Sucursal=checkBotonVilla.getText();
                  String Sucursal2=CheckBoxCoatza.getText();
                  String Sucursal3=checkBoxSanMartin.getText();
                  String Sucursal4=checkBoxSantaIsabel.getText();
        
               if (noEsAlphanumerico(nombreTextField.getText()) == false){
                try{
                 if(nombredelproducto.isEmpty()){
                        JOptionPane.showMessageDialog(this,"Por favor ingrese un nombre de producto, Mensaje de error al Ingresar dato");
                }else {
                        if(tipodelproducto.isEmpty()){
                     JOptionPane.showMessageDialog(this,"Por favor ingrese un tipo de producto, Mensaje de error al Ingresar dato");
           }else{
                    if ("".equals(cantidadProductoTextField.getText())){
                        
                         JOptionPane.showMessageDialog(this,"Por favor ingrese una cantidad del producto, Mensaje de error al Ingresar dato");
                    }else if (Integer.parseInt(cantidadProductoTextField.getText()) < 0){
                        JOptionPane.showMessageDialog(this,"Por favor ingrese una cantidad del producto numero positivo, Mensaje de error al Ingresar dato");
                    }
                        else {
                            
                                if(!"No hay ningun seleccionado".equals(this.getProveedor())){
                                    
                                        if(!"No hay ningun seleccionado".equals(this.getSucursal())){
                                            
                                                        JOptionPane.showMessageDialog(this,"Todos los datos fueron guardados correctamente :), A continuacion se le mostrara un resumen de su pedido");
                                                        Producto claseproducto=new Producto(nombredelproducto,tipodelproducto,Integer.parseInt(cantidadProductoTextField.getText()),getProveedor(),getSucursal());
                                                        
                                                        contenedor.add(claseproducto); 
                                                        
                                                        frmDatos mostrar=new frmDatos();
                                                        
                                                    mostrar.setVisible(true);
                                                    }else{
                                                            JOptionPane.showMessageDialog(this,"Por favor ingrese una sucursal, Mensaje de error al Ingresar dato");
                                                            } 
                                                                }else{
                                                                         JOptionPane.showMessageDialog(this,"Por favor ingrese un nombre del proveedor, Mensaje de error al Ingresar dato");
                                                                    }
                                                          } 
                                                                         
                                                        }
                        
                                                    } 
       }catch(HeadlessException e){
                System.out.println("Error atrapado");
            }
        
         }else{
                   JOptionPane.showMessageDialog(this,"Ingrese bien el nombre del producto");
               } 
        }catch(Exception e){
            System.out.println("No se ha ingrado datos,favor de ingresarlos al formulario");
             JOptionPane.showMessageDialog(this,"Mensaje de aviso: Por favor ingrese datos al formulario");
        }        
             
    }
     public String getProveedor()
     {
            if (this.radioBotonTomas.isSelected()) {
                return this.radioBotonTomas.getText();
            }
                else
            if (this.radioBotonRamon.isSelected()){
                return this.radioBotonRamon.getText();
            }
                else
            if (this.radioBotonJose.isSelected()) {
                     return radioBotonJose.getText();
            }
                else
            if (this.radioBotonLuis.isSelected()) {
                     return radioBotonLuis.getText();
                 }
                else
            if (this.RadioBotonHector.isSelected()) {
                 return RadioBotonHector.getText();
                }else
                    return "No hay ningun seleccionado";
      }
     public String getSucursal()
     {
        if (this.checkBotonVilla.isSelected()) {
                return this.checkBotonVilla.getText();
            }
                else
            if (this.CheckBoxCoatza.isSelected()){
                return this.CheckBoxCoatza.getText();
            }
             else
            if (this.checkBoxSanMartin.isSelected()) {
                 return checkBoxSanMartin.getText();
            }
                 else
            if (this.checkBoxSantaIsabel.isSelected()) {
                     return checkBoxSantaIsabel.getText();
                 }
                    else
                 return "No hay ningun seleccionado";
      }
   
public boolean noEsAlphanumerico(String texto){
boolean bandera = false;
for (int i = 0; i < texto.length(); i++) {
if (!caracter.isLetterOrDigit(texto.charAt(i))) {
bandera = true;
break;
}
}
if (bandera == true ) {
return true;
}
else
{
return false;
}
}


   
    
    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed
    
    private void jtipoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtipoboxActionPerformed
        String []productos= {"","Cubrebocas","Medicamento","analgesicos","pastillas","inyecciones","Cepillos de diente","Botiquín"};
        JComboBox listaDesplegable= new JComboBox();
        listaDesplegable.setBounds(20,20,100,30);
        
                
    }//GEN-LAST:event_jtipoboxActionPerformed

    private void radioBotonRamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonRamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonRamonActionPerformed

    private void radioBotonJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonJoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonJoseActionPerformed

    private void checkBoxSanMartinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSanMartinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSanMartinActionPerformed

    private void cantidadProductoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadProductoTextFieldKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Solo ingresar numeros ");
        }else{
            
                   
        }
    }//GEN-LAST:event_cantidadProductoTextFieldKeyTyped

    private void cantidadProductoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadProductoTextFieldActionPerformed
      
    }//GEN-LAST:event_cantidadProductoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxCoatza;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JRadioButton RadioBotonHector;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JTextField cantidadProductoTextField;
    private javax.swing.JCheckBox checkBotonVilla;
    private javax.swing.JCheckBox checkBoxSanMartin;
    private javax.swing.JCheckBox checkBoxSantaIsabel;
    private javax.swing.ButtonGroup grupoSucursal;
    private javax.swing.ButtonGroup grupoproveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jtipobox;
    public javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JRadioButton radioBotonJose;
    private javax.swing.JRadioButton radioBotonLuis;
    private javax.swing.JRadioButton radioBotonRamon;
    private javax.swing.JRadioButton radioBotonTomas;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new Ventanaprincipal().setVisible(true);
        }
    }
}
